### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lgatto** [lgatto/qcmetrics#1]
(Moved from README)

#### Reporting 
- [ ] TODO Bioc reportinTools
- [X] TODO Add metadata section
- [ ] TODO allow customisaton of meta-data section
- [ ] TODO Add a `save` arg to qcReport to save `object` and provide link in report.
- [ ] Improve nozzle report
- [ ] Dynamic reports could be created using `shiny`.
- [ ] Also look at arrayQualityMetrics report.
- [X] Report customisation
  - [X] pdf via different template 
  - [X] html via css
- [X] html, pdf
- [X] externalise the report-generating code into functions and 
      add a reporter argument to qcReport to provide custom reporting fuctions.

#### Applications
Illustrate the recipes/usage of `qcmetrics` on different types of data. 
- [X] Short QC pipelines for raw proteomics data
- [X] RNA degradation
- [X] Document the creation of new packages using `qcmetrics`.
- [ ] Add an example for RNASeq, see `ShortReads`
- [ ] QuaMeter idfree quality control

#### Serialisation 
- [X] Objects can of course be serialised with `save`, `saveRDS`.
- [ ] See if it is possible to interface with the `qcML` standard.

**Comment by Kohze** [comment]
I am quite familiar with QC pipelines from my freelancing work - they had a similar report generation code style. I`d like to take over the shiny part and explore what is possible in the next days and then from there look again what else we could implement reporting/input wise)

**Comment by Kohze** [comment]
I made a map evaluating how "qcmetrics" differs from rmarkdown reports itself. I think the unique feature is that it allows to algorithmicly define different sets of models and thereby analyzing and comparing large sets of experimental data (in a mostly unsupervised manner). Rmarkdown created documents may also allow to loop through reports directly, but its static and not programmaticly definable opposed to qcmetrics. 

![experience map](https://cloud.githubusercontent.com/assets/16598797/23976332/3a5eb8b6-09e7-11e7-834e-cb550e8072a8.png)

While its certainly possible to extend the functionality to create full shiny applications from the object inputs - a "qcmetrics" created interactive markdown style would probably most useful (as markdown can include shiny applications). 

![](https://rstudioblog.files.wordpress.com/2014/06/storms-003.png)

The main problem there is that the interactivity can apparently not be rendered into standalone.html/.js files (in theorie it could pre-render/parse all R responses to js) but still need to start a local shiny instance which makes "reporting" itself difficult and thereby would probably deviate to far from the core of the package idea. In consequence I’m not yet convinced of the benefit of a shiny gui implementation (but I am interested to hear other ideas).

![screenshot_26](https://cloud.githubusercontent.com/assets/16598797/23977953/94e5d42c-09f1-11e7-8d7d-bd9fae087f88.png)

**Comment by lgatto** [comment]
There hasn't been any work recently on this front, and it is not a priority. But interactive output reports would certainly be a nice features.
